### ISSUE TITLE
Erroneously encoding tilde to %7e in getRemoteUrl

### ISSUE THREAD

**Issue by parruc** [plone/Products.ATContentTypes#2]
RFC 3986 (http://www.ietf.org/rfc/rfc3986.txt) says:

   For consistency, percent-encoded octets in the ranges of ALPHA
   (%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E),
   underscore (%5F), or tilde (%7E) should not be created by URI
   producers and, when found in a URI, should be decoded to their
   corresponding unreserved characters by URI normalizers.

From python documentation talking about urllib.quote()

  Example: quote('/~connolly/') yields '/%7econnolly/'.

So python function does not work as required by RFC 3986. 
I'm opening a bug on python tracker too but we can solve this problem adding ~ to the safe characters in  Products.ATContentTypes.content.link.ATLink.getRemoteUrl

**Comment by jensens** [comment]
upstream bug
