### ISSUE TITLE
SyntaxError message 'return' outside function

### ISSUE THREAD

**Issue by plsm** [plone/Products.ATContentTypes#20]
I am installing a plone site.  The buildout script is fetching version 2.1.15 of ATContentyTypes. When it compiles this egg I get this type of syntax error messages:

    Compiling /usr/local/Plone-4.3.6/buildout-cache/eggs/Products.ATContentTypes-2.1.15-py2.7.egg/Products/ATContentTypes/skins/ATContentTypes/getXMLSelectVocab.py
      File "/usr/local/Plone-4.3.6/buildout-cache/eggs/Products.ATContentTypes-2.1.15-py2.7.egg/Products/ATContentTypes/skins/ATContentTypes/getXMLSelectVocab.py", line 26
        return "<div>%s</div>" % result_string.encode('utf-8')
SyntaxError: 'return' outside function

Does this means that the product was not installed correctly?

The file in question only has a return statement. I am not an expert in python, so I don't if this is a valid code.

I am using plone version 4.3.6

**Comment by gforcada** [comment]
No, don't worry. This is not a proper python module on purpose. The return statement is inside a skins folder which is treated specially within Zope/Plone.
